/**
 * @file image.h
 * @brief Header file for processing image dataset.
 * @kaspersky_support D. Postnikov
 * @date 14.07.2025
 * @license Apache 2.0
 * @copyright © 2025 AO Kaspersky Lab
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <knp/core/core.h>
#include <knp/core/impexp.h>
#include <knp/core/messaging/messaging.h>

#include <vector>

#include "dataset.h"


/**
 * @brief Namespace for image classification data processing.
 */
namespace knp::framework::data_processing::classification::images
{

/**
 * @brief The `Dataset` class is a definition of an interface to processed dataset of images.
 */
class KNP_DECLSPEC Dataset final : public classification::Dataset
{
public:
    /**
     * @brief Process labels and images, converting the images to spike form and creating data pairs.
     * @param images_stream stream containing the raw image data.
     * @param labels_stream stream containing the corresponding labels.
     * @param training_amount desired number of images to use for training.
     * @param classes_amount total number of classes in the dataset.
     * @param image_size size of each image in bytes.
     * @param steps_per_image number of steps required to transmit an image in spike form to a model.
     * @param image_to_spikes function that converts raw image data to spike form, returning a `Frame` object.
     * @details This method reads images and labels from the provided streams, converts each image to spike form 
     * using the provided converter function, and creates data pairs consisting of the label and spike frame. 
     * The data pairs are added to the training dataset.
     */
    void process_labels_and_images(
        std::istream &images_stream, std::istream &labels_stream, size_t training_amount, size_t classes_amount,
        size_t image_size, size_t steps_per_image,
        std::function<Frame(std::vector<uint8_t> const &)> const &image_to_spikes);

    /**
     * @brief Create a generator that produces spike data from training labels.
     * @return functor for generating spikes from training labels.
     * @details The generated spike data is created by iterating over the training labels in a loop, with each label repeated at regular intervals.
     */
    [[nodiscard]] std::function<knp::core::messaging::SpikeData(knp::core::Step)> make_training_labels_generator()
        const;

    /**
     * @brief Create a generator that produces spike data from training images.
     * @return functor for generating spikes from training images.
     * @details The spike data is generated by iterating over the training images in a looped manner, where each image is divided into
     * frames. For each frame, the corresponding spike data is extracted and returned.
     */
    [[nodiscard]] std::function<knp::core::messaging::SpikeData(knp::core::Step)>
    make_training_images_spikes_generator() const;

    /**
     * @brief Create a generator that produces spike data from inference images.
     * @return functor for generating spikes from inference images.
     * @details The spike data is generated by iterating over the inference images in a looped manner, where each image is divided into
     * frames. For each frame, the corresponding spike data is extracted and returned.
     */
    [[nodiscard]] std::function<knp::core::messaging::SpikeData(knp::core::Step)>
    make_inference_images_spikes_generator() const;

    /**
     * @brief Create an incrementing image to spikes converter.
     * @details This converter generates spikes based on the input image data, considering the specified number of active steps
     * and the state increment factor. Spikes are sent for the active steps, and no spikes are sent for the remaining steps
     * until the total steps per image (@ref steps_per_frame_) are reached.
     * @param active_steps number of active steps, which must be less than the total steps per image (@ref steps_per_frame_).
     * @param state_increment_factor factor by which the state is incremented for each input value.
     * @return functor that converts raw image data to spikes.
     */
    [[nodiscard]] std::function<Frame(std::vector<uint8_t> const &)> make_incrementing_image_to_spikes_converter(
        size_t active_steps, float state_increment_factor) const;

    /**
     * @brief Get image size.
     * @return image size.
     */
    [[nodiscard]] size_t get_image_size() const { return image_size_; }

protected:
    /**
     * @brief Total image size.
     */
    size_t image_size_ = 0;
};


}  // namespace knp::framework::data_processing::classification::images
